### ISSUE TITLE
Watching parent directories?

### ISSUE THREAD

**Issue by feuerbach** [haskell-fswatch/hfsnotify#41]
Here's something I want to implement, but I'd like to have some feedback, just in case I'm missing something or there's a better solution.

This is related to #32. Suppose I want to watch a path. As far as I understand, neither Windows nor Linux allow to watch a path. Windows only allows to watch a directory, and Linux allows to watch a file (identified by the inode) but not the path.

So, in either case we'll have to also watch the parent directory.

Now, the immediate parent directory itself may be replaced or even not exist when we start watching. So the question is, should we watch every single directory up the tree?

Here's an example of what I mean. Remember, I'm interested in whatever happens
under a certain path. Let's say it's `/foo/bar/baz`, and only `/foo` exists at
the moment. `/foo/bar/baz` may appear as a result of the following:

```
mkdir /foo/bar
touch /foo/bar/baz
```

To catch this, we must first watch for `/foo`, and after `/foo/bar` is created,
check and watch for `/foo/bar/baz`. Moreover, the following may happen later:

```
rm -rf /foo
mkdir -p /foo/bar
touch /foo/bar/baz
```

Which means that we must either watch every single directory up the tree, or
readjust the watchlist dynamically if things get deleted/moved (i.e. start
watching `/` when `/foo` is deleted, to catch creation of a new `/foo`).

Am I overcomplicating things here? I feel that watching a path is what the user
usually means, and we should expose a simple and intuitive API, even at the cost
of internal complexity (which is caused by os-level API being too low-level).

**Comment by thomasjm** [comment]
Cleaning up old issues now, I think I'll close this one since there doesn't seem to be a definite proposal. I think the original issue is solved by the recursive watch functions (using `watchTree` etc. on a folder high enough that it always exists).
