### ISSUE TITLE
Check rtsSupportsBoundThreads to ensure threaded runtime present on Windows

### ISSUE THREAD

**Issue by ndmitchell** [haskell-fswatch/hfsnotify#50]
I tried the API, but it breaks the stdout stream in some weird way. Using the example at the top of the docs, plus a call to set the stdout to NoBuffering, when run from `runhaskell` I get each event printed (with some output interleaved, but that's expected without buffering or locking). When compiled and run I see `M` after about 5 modifications, which likely is the start of `Modified`. In previous larger examples I've had it print out 1 character on each change, even though each change generates a line of output.

**Comment by ndmitchell** [comment]
Without wanting to seem fatalistic, this package is broken on all three Windows machines I have, both Win7 and Win8.1. It always trashes the stdout, and also any open file handles. If this really sucks on Windows, and no one is going to fix it, perhaps put that in a big warning before others who come after me also waste their time.

**Comment by gregwebs** [comment]
do you want to send a PR for the README? You can edit it inline on github.

When this package was originally created it was tested to work on windows. So I don't know if the testing was not good enough or the package or GHC changed. It is possible if you put your test case here this issue might get fixed sooner (than never :))

**Comment by ndmitchell** [comment]
Sorry, it's frustrating to have sunk a fair bit of time into refactoring assuming an API will work, and then finding it always trashes the process beyond repair.

Given:

    import System.FSNotify
    import System.IO
    import System.Directory
    import Data.String
    import Control.Concurrent

    main = withManager $ \manager -> do
        hSetBuffering stdout NoBuffering
        dir <- getCurrentDirectory
        print "BEFORE REGISTERED"
        watchDir manager (fromString dir) (const True) $ \event -> print "EVENT FIRED"
        print "AFTER REGISTERED"
        print "AFTER REGISTERED 2"
        threadDelay $ 100 * 1000000

Compiled with GHC 7.8.3 at `-O0` and run I get the output:

    "BEFORE REGISTERED"
    "

Modifying that source file (to raise events) changes the last line to:

    "AFT

10 further saves gives:

    "AFTER"

Nothing further changes the output. Ctrl-C does not work. The stdout seems to have been completely broken, and quite possibly the whole input/output subsystem of GHC.

**Comment by ndmitchell** [comment]
On a hunch, I added `-threaded`, which seems to make it come back to life and work quite reliably. I thought I'd tried that before without success, but maybe not...

Is the `-threaded` requirement documented? Is it required for Linux as well? Perhaps document it and raise an error if not compiled with `-threaded`, as it really does trash everything.

**Comment by gregwebs** [comment]
ahh, I think I remember there being -threaded issues. Something about using the FFI on Windows needing -threaded. I don't know if that is the case on other platforms. Certainly lets document this. How does one raise an error if there is no `-threaded` ?

**Comment by ndmitchell** [comment]
`rtsSupportsBoundThreads` - see http://stackoverflow.com/questions/22839824/how-to-detect-if-a-program-has-been-compiled-using-threaded. I've certainly used Windows FFI without `-threaded` and never seen the weird behavior above - I suspect it's callbacks or some such in conjunction with the FFI.

**Comment by gregwebs** [comment]
@mlacorte
When you are done with your refactoring I want to add a check for rtsSupportsBoundThreads. I am not sure where the optimal place for it is. Right now I might put it in `initSession`.

**Comment by thomasjm** [comment]
Just to be clear, the plan was to check `rtsSupportsBoundThreads` and throw a clear error message when we're on Windows without `-threaded`, right?

**Comment by ndmitchell** [comment]
Yes.
