### ISSUE TITLE
Using Debounce can result in missing critical events

### ISSUE THREAD

**Issue by mlacorte** [haskell-fswatch/hfsnotify#55]
##### Description

Under certain conditions, such as rapidly deleting and writing a file, hfsnotify may fail to report on critical events, potentially leaving the program running hfsnotify in a broken state.
##### Steps to Reproduce
1. Run the following Bash script:
   
   ``` bash
   mkdir -p /tmp/example
   ```
2. Run the following Haskell program:
   
   ``` haskell
   {-# LANGUAGE OverloadedStrings #-}
   
   import System.FSNotify
   import Control.Concurrent
   import Control.Monad
   
   main :: IO ()
   main = withManagerConf defaultConfig { confDebounce = Debounce 1 } $ \mgr -> do
      _ <- watchDir mgr "/tmp/example" (const True) print
      forever (threadDelay maxBound)
   ```
3. While the Haskell program is running, run the following Bash script:
   
   ``` bash
   cd /tmp/example
   
   touch foo
   sleep 1
   
   rm foo
   touch foo
   sleep 1
   
   rm foo
   ```
##### Expected Output

```
Added (FilePath "/tmp/example/foo") <TIMESTAMP>
Removed (FilePath "/tmp/example/foo") <TIMESTAMP>
Added (FilePath "/tmp/example/foo") <TIMESTAMP>
Removed (FilePath "/tmp/example/foo") <TIMESTAMP>
```
##### Actual Output

```
Added (FilePath "/tmp/example/foo") <TIMESTAMP>
Removed (FilePath "/tmp/example/foo") <TIMESTAMP>
Removed (FilePath "/tmp/example/foo") <TIMESTAMP>
```
##### Discussion/Proposal

I was a little hesitant to call this a "bug" since hfsnotify is technically behaving as advertised.

I decided to label it as such since I believe that most users of the library expect it to accurately keep track of the current state of the filesystem, and in that regard, this would be considered a failure to behave as expected.

My proposal to correct this behavior is to accumulate change events over the specified debounce time interval and apply the following logic to them:

![State Transition Table](https://cloud.githubusercontent.com/assets/2569502/5981263/82fb0dbe-a86d-11e4-9e70-f5f6335ea851.png)

Note that "Impossible" errors cannot be reached, and the "File already exists" and "File does not exist" errors can only be reached if the notification manager is returning bad results (ex: two `Added` events in a row).

The following is an example implementation of the proposed logic:

``` haskell
-- It is assumed that all events passed into this function have the same eventPath
combineEvents :: Bool -> [Event] -> Maybe Event
combineEvents fileExists = snd . foldl logic (fileExists, Nothing)
  where
    -- Combining logic
    logic (True  , Nothing            ) (Modified fp t) = (True  , Just (Modified fp t))
    logic (True  , Nothing            ) (Removed  fp t) = (False , Just (Removed  fp t))
    logic (False , Nothing            ) (Added    fp t) = (True  , Just (Added    fp t))
    logic (True  , Just (Added    _ _)) (Modified fp t) = (True  , Just (Added    fp t))
    logic (True  , Just (Added    _ _)) (Removed   _ _) = (False , Nothing             )
    logic (True  , Just (Modified _ _)) (Modified fp t) = (True  , Just (Modified fp t))
    logic (True  , Just (Modified _ _)) (Removed  fp t) = (False , Just (Removed  fp t))
    logic (False , Just (Removed  _ _)) (Added    fp t) = (True  , Just (Modified fp t))

    -- If you see these, it means your notification manager is broken
    logic (True  , _                  ) (Added     _ _) = error "File already exists"
    logic (False , _                  ) (Modified  _ _) = error "File does not exist"
    logic (False , _                  ) (Removed   _ _) = error "File does not exist"

    -- If you see these, it means this function's logic is broken
    logic (True  , Just (Removed  _ _)) _               = error "Impossible"
    logic (False , Just (Added    _ _)) _               = error "Impossible"
    logic (False , Just (Modified _ _)) _               = error "Impossible"
```

While these changes don't have a significant impact on small debounce time intervals, this would allow time intervals that are seconds, minutes, or even hours long to be specified while still reporting the correct state of the filesystem.

The only downside to this approach is that you have to wait the specified debounce time interval before first receiving a change notification, however, I think this change would be considered acceptable in almost all use cases.

**Comment by gregwebs** [comment]
For some use cases one just wants to know if something happened and would like that information as soon as possible. So the ideal would probably be to allow for applying the logic you have here but also allow for a quick notification mode.

**Comment by thomasjm** [comment]
Closing this since debounce is removed from the next version.

Thanks for the idea for the state machine though, it will hopefully be worked into an optional module in the future!
