### ISSUE TITLE
DISCUSSION: Breaking changes

### ISSUE THREAD

**Issue by mlacorte** [haskell-fswatch/hfsnotify#56]
I'm working on a Haskell project that requires cross-platform filesystem notifications, and unfortunately, hfsnotify doesn't currently provide all the features that I need.

I'm going to begin work on a fork that will include the following breaking changes:
- Add `Moved FilePath FilePath UTCTime` constructor to `Event`
- Rename `eventPath` to `eventOrigin`
- Add `eventDestination`
- Update fsnotify to report on changes made to directories
- Update reporting logic to account for the tracking of changes to directories

If these are changes you'd like included in hfsnotify, I'm open to discussing changes to their semantics, however I require both the "move" and "directory" changes for what I'm working on, so they come as a set. If you want just one of them, you'll have to backport it from my fork.

I'll make a pull request when I believe it's stable on Linux, OS X, and Windows. This ticket is just a heads-up so that there is more time to discuss the implications/semantics of these changes.

**Comment by gregwebs** [comment]
fsnotify could definitely use some of the improvements you are adding. I am fine with breaking changes in general: we just need to bump the cabal version.

**Comment by mlacorte** [comment]
Would you also be comfortable with me adding a `WatchManagerClosed` exception, or something similar? Right now adding listeners to a stopped `WatchManager` fails silently.

**Comment by gregwebs** [comment]
Conceptually yes, errors should not be silent. As an implementation detail it may be better to return an Either instead of throwing, or at least provide that as an option. It kind of depends on how many exceptions can already be thrown.

**Comment by feuerbach** [comment]
I'd say that an exception should be used for this. Typically you do know that the manager is not closed, since you haven't closed it. So it is really an exceptional situation.

Contrast this with a problem like parsing, where you have no idea whether the input will be valid at runtime.

**Comment by mlacorte** [comment]
Regarding @gregwebs's question about existing exceptions, I haven't started digging into the OS dependent notification libraries yet, so I don't have a great answer for that right now, but I'll make sure to compile a list of every error this library can throw so that we can, at the very least, add those to the documentation.

A few known ones off the top of my head are:

* Watching a directory that doesn't exist
* Watching a directory without correct permissions
* Threads randomly dying

...and I'm sure there are plenty more.

I will also be adding a new one for collapsing multiple conflicting events, such as `combine (Moved "a" "b") (Moved "a" "c")`.

Regarding exceptions vs types for this particular instance, while I lean slightly towards exceptions since there's a notion of a "normal/expected" path, so long as all errors are being reported, I don't have particularly strong feelings about the delivery mechanism. The only thing I ask is that a queriable type also be thrown along with the human-readable string so that different exceptions can be easily caught/handled.

**Comment by gregwebs** [comment]
Oh, right, I would use an exception in this case

**Comment by mlacorte** [comment]
Another thing.

There's currently some logic in place to fall back to the `PollManager` if the `NativeManager` fails to initialize, but the way `fsnotify` is coded, these failures cannot be triggered. It will either succeed as expected or fail with an exception that is not caught by the fallback logic, rendering the fallback logic useless.

My question is, should I cause `NativeManager` initialization failures to trigger the fallback logic, or should I do away with the fallback entirely?

I'm of the opinion that this logic should be removed for a few reasons:

* The majority of all failures will be caused by bad paths and permission errors, and falling back to a `PollManager` will not fix either of those issues.
* I think fail-fast systems are a better design, and including the fallback logic might constitute a silent failure in the user's code if they aren't aware that the logic exists and they expect certain characteristics only provided by the `NativeManager`.

I actually can't think of an instance where the `NativeManager` would fail to start, but the `PollManager` would succeed beyond there being a bug in `fsnotify` or some catastrophic OS error.

**Comment by gregwebs** [comment]
I think a main use case where polling doesn't always work is when the file system is mounted. The ideal would probably be able to have the options of turning fallback on or off. But if it isn't even working as you say then removing it may be good.

**Comment by mlacorte** [comment]
Network mounted filesystems are a case I hadn't considered and are a good argument for keeping the fallback. The code for the fallback logic is very minimal, so don't worry about factoring that into the decision.

My vote's still for disabling it by default based solely on the fail-fast principle, but given how this could be useful for someone using network mounted filesystems, I think allowing a configuration parameter to turn it on would get us the best of both worlds.

**Comment by winterland1989** [comment]
I came across this library recently during building a sync tool, any progress there @mlacorte ?

**Comment by winterland1989** [comment]
One problem is Win32-notify package do not provide MOVE event, while we want keep fsnotify platform-independent...

**Comment by mlacorte** [comment]
Yes, I'm still actively working on this, but it's been taking me longer than I had initially anticipated. My goal is to create a clean enough abstraction that the library will work more-or-less identically no matter which filesystem watcher you are using, so most of my effort has gone into working out all the quirks of the various filesystems/filesystem watchers.

I've found that writing unit tests to act merely as sanity checks has so far failed to uncover all the various edge cases that have come up throughout the process of me working on these enhancements, so I'm currently in the process of writing a property-based series of tests that are expected to hold across all filesystems/watchers.

Once these are done, my hope is that this will become more a process of "fill in the blanks", rather than "write some naive code, only to uncover yet-another edge case".

I don't have a good estimate of when I'm going to be done yet, but I wouldn't expect it to be any earlier than a month from now.

**Comment by winterland1989** [comment]
@mlacorte glad to hear you are working on this, assign issue to me if you wish, hope things go well ：)

**Comment by mlacorte** [comment]
@winterland1989 My version of the code isn't on Github right now since it's in a half-baked state, but if you'd be interested in helping, I'll clean it up a bit and push it to a fork so that you we can collaborate on it. I don't have time to work on this today, but I'll have a working version up by tomorrow.

Until then, you could start by adding the following `Event`/`EventVariety` types to the [Win32-notify](https://hackage.haskell.org/package/Win32-notify) package:

* Renamed
  * isDirectory
  * filepathOrig
  * filepath
* Accessed
  * isDirectory
  * filepath
* StatusChanged
  * isDirectory
  * filePath

**Comment by simonmichael** [comment]
@mlacorte ping, any progress ?

**Comment by mlacorte** [comment]
The more I dug, the more problems I kept running into trying to get everything working correctly, so I gave up and changed the requirements on my end. Sorry for the anti-climax.

**Comment by simonmichael** [comment]
No problem, thank you. If you come across any of your changes that would work well as PRs to this project, I'm sure they'd be appreciated.

**Comment by thomasjm** [comment]
Cleaning up old issues now. I'm going to close this since there's nothing actionable here. (Great discussion, I might mine this later to open a few issues about fallback to polling, exceptions, more expressive events, etc.)
