### ISSUE TITLE
Interest in switching to filepath?

### ISSUE THREAD

**Issue by MichaelXavier** [haskell-fswatch/hfsnotify#57]
It seems like filepath has been shipping with GHC for a long time and that system-filepath has been deprecated in favor for it. It looks like it goes back to using a String alias, so I wanted to check with the project and see if there was any interest in a PR that would switch to the filepath package.

**Comment by gregwebs** [comment]
Sounds good

**Comment by davean** [comment]
I for one look forward to this making a release version.

**Comment by MichaelXavier** [comment]
Anything holding back the merge, @gregwebs ?

**Comment by gregwebs** [comment]
Thanks for the reminder. Merged

**Comment by gregwebs** [comment]
uploaded to hackage as 0.2
