### ISSUE TITLE
Events are executed concurrently

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell-fswatch/hfsnotify#64]
Hi, the `watchDir`/`watchTree` docs say: 

> No two events pertaining to the same FilePath will be executed concurrently.

However, I've found that not to be the case:

``` haskell
import Control.Concurrent
import System.FSNotify

main = withManager $ \wm -> do
    watchDir wm "." (const True) $ \ev -> do
        putStrLn ("Handling " ++ eventPath ev)
        threadDelay 2000000
        putStrLn "Done"
    _ <- getLine
    pure ()
```

Firing up a terminal and running `touch foo; touch foo;` within two seconds, I see:

```
Handling /Users/mrosen/junk/foo
Handling /Users/mrosen/junk/foo
Done
Done
```

but I'd expect to see

```
Handling /Users/mrosen/junk/foo
Done
Handling /Users/mrosen/junk/foo
Done
```

Am I misunderstanding the docs here? Thanks.

**Comment by gregwebs** [comment]
seems like a bug to me.

**Comment by mitchellwrosen** [comment]
It actually turns out for my use case I _want_ FSNotify to call the callback no matter if the previous one hasn't completed yet. So, I'm relying on this bug for now. I'm on OSX by the way.

**Comment by mitchellwrosen** [comment]
Hi, @bsummer4 looked into this for a bit yesterday. Each event is quite clearly being handled by a separate thread, see https://github.com/haskell-fswatch/hfsnotify/blob/master/src/System/FSNotify.hs#L224.

But again, this behavior doesn't seem undesirable to me, although it is inconsistent with the documentation.

**Comment by abailly** [comment]
I am a bit late to the party, but thanks for investigating this. I *do* rely on events not being fired concurrently and have been puzzled for a while with the behaviour for my program as I also read the documentation saying explicitly events were not handled concurrently.

**Comment by mitchellwrosen** [comment]
@abailly I'd use the `Chan` version rather than the callback version, and just read events as necessary

**Comment by abailly** [comment]
Thanks for the tip. Definitely a route I should follow... I was thinking of
implementing a channel myself and overlooked the fact it was already there
:-)

Le 15 sept. 2016 16:50, "Mitchell Rosen" <notifications@github.com> a
écrit :

**Comment by tolgap** [comment]
I'm running into this issue now. I really need synchronous callbacks because I'm recompiling stuff on change and a recompile could take some time.

Is there a workaround for this? I don't see how using `chan` would remedy this. Thanks.

**Comment by mitchellwrosen** [comment]
@tolgap Use e.g. `watchTreeChan`, which pushes file system events to a `Chan`. Then, you can read from this `Chan` as often as necessary.

**Comment by thomasjm** [comment]
It turns out the documentation was just out of date, I've removed the locking claim now. See #43 for more on locking.
