### ISSUE TITLE
Support hinotify master

### ISSUE THREAD

**Issue by avieth** [haskell-fswatch/hfsnotify#75]
`hinotify` now uses `ByteString` rather than `[Char]` for file paths (`RawFilePath`).

https://github.com/kolmodin/hinotify/issues/19
https://github.com/kolmodin/hinotify/commit/106930cae1bc8dc8ab6041816c11eafa72387cfe

~~Somehow this didn't make it into the changelog for that package.~~ because it's not yet released :)

**Comment by jchia** [comment]
`hinotify` switched to `RawFilePath` in [11c4d31a95ad36f954fac6728e47042a92e4466a](https://github.com/kolmodin/hinotify/commit/11c4d31a95ad36f954fac6728e47042a92e4466a). Previously, it was using `GHC.IO.Encoding.getFileSystemEncoding` together with `GHC.Foreign.withCString` to convert from `ByteString` to . Now that `hinotify` is no longer doing that decoding, should `hsnotify` start doing it for newer versions of `hinotify`?
