### ISSUE TITLE
Update CHANGELOG?

### ISSUE THREAD

**Issue by byorgey** [haskell-fswatch/hfsnotify#79]
Hi there!  It's nice to see all the work happening on `hfsnotify`.  With the recent 0.3 release it would be nice to know what has changed since version 0.2.x, to give me a better idea of what I might need to do to upgrade to the newest version.  (See also https://github.com/commercialhaskell/stackage/issues/3678 .) Thanks!

**Comment by thomasjm** [comment]
Good call, done!

**Comment by byorgey** [comment]
Thanks!
