### ISSUE TITLE
build failure, directory bounds need updating

### ISSUE THREAD

**Issue by simonmichael** [haskell-fswatch/hfsnotify#84]
fsnotify-0.3.0.1 (eg) still depends on directory (>=1.1.0.0), but it uses doesPathExist which was introduced in directory-1.2.7.0.

**Comment by howtonotwin** [comment]
This has bitten me also. It appears that the bound needs to be revised all the way back to `fsnotify-0.2.1`.

**Comment by thomasjm** [comment]
I just fixes this for future releases. I'm not sure to revise older versions, I think you need to be a Hackage administrator...

**Comment by Bodigrim** [comment]
As a Hackage trustee I made requested revisions:
https://hackage.haskell.org/package/fsnotify-0.3.0.0/revisions/
https://hackage.haskell.org/package/fsnotify-0.3.0.1/revisions/
