### ISSUE TITLE
Allow debouncing regardless of if event is same file

### ISSUE THREAD

**Issue by codygman** [haskell-fswatch/hfsnotify#90]
I have a use case where I just want to debounce for a time interval and not care about if it's the same file.

Say I modify `a.hs`, `b.hs`, and `c.hs` in my editor. Then I save them all at once. The action that I have specified will be run 3 times.

**Comment by codygman** [comment]
We probably want to add a `CustomDebounce (Event -> Bool)` case to the [Debounce sum type](https://github.com/haskell-fswatch/hfsnotify/blob/91c862b93a910927b138884c2f3807f72067605b/src/System/FSNotify/Types.hs#L71).

**Comment by thomasjm** [comment]
Hi @codygman, sorry for the delay. It's actually an explicit goal of this library at the moment to decouple and remove debouncing support. Debouncing is really orthogonal to file watching, so it's not this library's place to do it, even though historically it has.

It's recommended to disable debouncing on this library and do your own debouncing in your event handler.

**Comment by codygman** [comment]
> Debouncing is really orthogonal to file watching

Can you expand on this? How is it orthogonal in your opinion?

**Comment by thomasjm** [comment]
I simply mean a library should do one thing and do it well. This is a library for watching files and firing events when they change. Debouncing is a separate concern that can be managed independently (with your own custom code, or with another library like [Control.Debounce](http://hackage.haskell.org/package/auto-update-0.1.6/docs/Control-Debounce.html)).

**Comment by thomasjm** [comment]
Tidying up old issues, going to close this one as wontfix.
