### ISSUE TITLE
Fire event variety "CloseWrite"

### ISSUE THREAD

**Issue by docteurklein** [haskell-fswatch/hfsnotify#99]
I noticed that http://unisonweb.org 's UCM tool does not re-read my scratch file when entering it and then doing a save.
I noticed a similar comment (although talking about WSL) https://github.com/haskell-fswatch/hfsnotify/issues/74#issuecomment-386076622  but I'm on linux and I would like this event to be observable, so that I could fix UCM downstream.

Any reason why this event is not listed in https://github.com/haskell-fswatch/hfsnotify/blob/master/src/System/FSNotify/Linux.hs#L84 ?

In any case, thanks for reading :)

EDIT: I use `-e close_write` instead of `-e modify` when writing `inotifywait` shell scripts and it usually works better; it basically subsumes `modify` behavior and does what you expect.

**Comment by thomasjm** [comment]
> Any reason why this event is not listed

Not particularly--the main reason is that this library was written to be platform-independent, so events need to ultimately get mapped to the platform-independent `Event` type in `System.FSNotify.Types`. So events that don't have direct equivalents on all platforms weren't added historically.

However, I don't think we actually need an event to be supported on all platforms in order for it to be useful. For example, I recently added the `ModifiedAttributes` event on `master` branch. We could do the same thing to add a new `CloseWrite` event that only gets fired on Linux.

Would you like to make a PR?

**Comment by thomasjm** [comment]
FYI I just pushed support for this in e4ba64c3bc1084ba7efeffde95582ec416bc5c66

**Comment by docteurklein** [comment]
thanks a lot :)
